# templates/deployment-taskmanager.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink-cdc.fullname" . }}-taskmanager
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
    app.kubernetes.io/component: taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicas }}
  selector:
    matchLabels:
      {{- include "flink-cdc.taskmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flink-cdc.taskmanager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flink-cdc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          args: ["taskmanager"]
          env:
            - name: FLINK_CONF_DIR
              value: /opt/flink/conf
            - name: MSSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.mssqlCredentials.name }}
                  key: {{ .Values.existingSecrets.mssqlCredentials.usernameKey }}
            - name: MSSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.mssqlCredentials.name }}
                  key: {{ .Values.existingSecrets.mssqlCredentials.passwordKey }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.externalServices.minio.endpoint | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.minioCredentials.name }}
                  key: {{ .Values.existingSecrets.minioCredentials.accessKeyKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecrets.minioCredentials.name }}
                  key: {{ .Values.existingSecrets.minioCredentials.secretKeyKey }}
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.taskmanager.ports.rpc }}
              name: rpc
            - containerPort: {{ .Values.taskmanager.ports.data }}
              name: data
          livenessProbe:
            tcpSocket:
              port: {{ .Values.taskmanager.ports.rpc }}
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            tcpSocket:
              port: {{ .Values.taskmanager.ports.rpc }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.taskmanager.resources | nindent 12 }}
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
            - name: flink-lib
              mountPath: /opt/flink/lib
            {{- if .Values.persistence.enabled }}
            - name: flink-data
              mountPath: /opt/flink/data
            {{- end }}
            - name: flink-log
              mountPath: /opt/flink/log
      volumes:
        - name: flink-config-volume
          configMap:
            name: {{ include "flink-cdc.fullname" . }}-config
            items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j-console.properties
                path: log4j-console.properties
        - name: flink-lib
          emptyDir: {}
        - name: flink-log
          emptyDir: {}
        {{- if .Values.persistence.enabled }}
        - name: flink-data
          persistentVolumeClaim:
            claimName: {{ include "flink-cdc.fullname" . }}-data
        {{- end }}
---
