# templates/monitoring.yaml
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink-cdc.fullname" . }}-prometheus-config
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
data:
  flink-metrics.yaml: |
    # This file controls the Flink metrics configuration
    # The configuration is maintained in this ConfigMap
    metrics.reporters: prom
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.port: 9249

{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flink-cdc.fullname" . }}
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flink-cdc.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}

{{- if .Values.monitoring.prometheusRule.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "flink-cdc.fullname" . }}
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
spec:
  groups:
    - name: flink.rules
      rules:
        - alert: FlinkJobFailing
          expr: flink_jobmanager_job_numRestarts > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Flink job is failing"
            description: "Flink job {{ $labels.job_name }} ({{ $labels.job_id }}) has restarted {{ $value }} times in the last 5 minutes."
        - alert: FlinkTaskManagerNotRunning
          expr: sum(up{job="flink-taskmanager"}) < {{ .Values.taskmanager.replicas }}
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "TaskManager not running"
            description: "One or more TaskManagers are not running."
        - alert: FlinkJobManagerNotRunning
          expr: sum(up{job="flink-jobmanager"}) < 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "JobManager not running"
            description: "The JobManager is not running."
{{- end }}
{{- end }}
---/_helpers.tpl
---
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "flink-cdc.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "flink-cdc.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "flink-cdc.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "flink-cdc.labels" -}}
helm.sh/chart: {{ include "flink-cdc.chart" . }}
{{ include "flink-cdc.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "flink-cdc.selectorLabels" -}}
app.kubernetes.io/name: {{ include "flink-cdc.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
JobManager selector labels
*/}}
{{- define "flink-cdc.jobmanager.selectorLabels" -}}
{{ include "flink-cdc.selectorLabels" . }}
app.kubernetes.io/component: jobmanager
{{- end }}

{{/*
TaskManager selector labels
*/}}
{{- define "flink-cdc.taskmanager.selectorLabels" -}}
{{ include "flink-cdc.selectorLabels" . }}
app.kubernetes.io/component: taskmanager
{{- end }}

{{/*
SQL Gateway selector labels
*/}}
{{- define "flink-cdc.sqlgateway.selectorLabels" -}}
{{ include "flink-cdc.selectorLabels" . }}
app.kubernetes.io/component: sqlgateway
{{- end }}

{{/*
CDC Gateway selector labels
*/}}
{{- define "flink-cdc.cdcgateway.selectorLabels" -}}
{{ include "flink-cdc.selectorLabels" . }}
app.kubernetes.io/component: cdcgateway
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "flink-cdc.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "flink-cdc.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
---