# templates/route.yaml (OpenShift specific)
---
{{- if .Values.jobmanager.highAvailability.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "flink-cdc.fullname" . }}-jobmanager
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
spec:
  port:
    targetPort: ui
  to:
    kind: Service
    name: {{ include "flink-cdc.fullname" . }}-jobmanager
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
---