# templates/secrets.yaml
---
{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecrets.mssqlCredentials.name }}
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.existingSecrets.mssqlCredentials.usernameKey }}: {{ .Values.mssqlAuth.username | b64enc }}
  {{ .Values.existingSecrets.mssqlCredentials.passwordKey }}: {{ .Values.mssqlAuth.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecrets.minioCredentials.name }}
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.existingSecrets.minioCredentials.accessKeyKey }}: {{ .Values.minioAuth.accessKey | b64enc }}
  {{ .Values.existingSecrets.minioCredentials.secretKeyKey }}: {{ .Values.minioAuth.secretKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecrets.kafkaCredentials.name }}
  labels:
    {{- include "flink-cdc.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.existingSecrets.kafkaCredentials.usernameKey }}: {{ .Values.kafkaAuth.username | b64enc }}
  {{ .Values.existingSecrets.kafkaCredentials.passwordKey }}: {{ .Values.kafkaAuth.password | b64enc }}
{{- end }}
---